pipeline {
    agent any
    stages{
        stage('Checkout'){
            steps{checkout scm}
        }
        stage('Install and Test'){
            steps {
               
                sh '/usr/bin/python3.8 -m venv .venv'
                sh '. .venv/bin/activate && pip install -r requirements.txt'
                sh '. .venv/bin/activate && pytest api-tests ...'
            }
        }
        stage('Run API tests'){
            steps{sh '. .venv/bin/activate && pytest api-tests -q --tb=short --html=reports/api-report.html'}
        }
        stage('Run UI tests'){
            steps{sh '. .venv/bin/activate && pytest ui-tests -q --tb=short --html=reports/ui-report.html'}
        }
    }
    post{
        always {archiveArtifacts artifacts: "reports/*.html", fingerprint: true}
    }
}