pipeline {
    agent any
    stages{
        stage('Checkout'){
            steps{checkout scm}
        }
        stage('Install'){
            steps{sh 'python3 -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt'}
        }
        stage('Run API tests'){
            steps{sh '. .venv/bin/activate && pytest api-tests -q --tb=short --html=reports/api-report.html'}
        }
        stage('Run UI tests'){
            steps{sh '. .venv/bin/activate && pytest ui-tests -q --tb=short --html=reports/ui-report.html'}
        }
    }
    post{
        always {archiveArtifacts artifacts: "reports/*.html", fingerprint: true}
    }
}